orm:
    strict: true
    cache: memcache
    adapter: SimpleDB
    date_format: Y-m-d H:i:s
    escaping: true
    schema: default
    
memcache:
    host: 127.0.0.1
    username: ~
    password: ~

amazon:
    access_key: 
    secret_key: 
    timeout: 5

mongodb:
     host: ~
     port: ~
     database: orm
     username: ~
     password: ~
