orm:
    strict: true
    cache: memcache
    adapter: MongoDB
    
memcache:
    host: 127.0.0.1
    username: ~
    password: ~

amazon:
    access_key: 
    secret_key: 

mongodb:
     host: ~
     port: ~
     database: test
     username: ~
     password: ~
